### PR TITLE
Depembeds bin

### PR DESCRIPTION
**Pull request by sebpuetz**
Depends on #23 

Adds the last piece to train dependency embeddings!

### CODE REVIEW

**Comment by danieldk** [comment]
I think that the last commit has to be rebased on mater, since this PR now also has the commit that I just merged in master (albeit with a different SHA hash).

**Comment by sebpuetz** [comment]
Thought the commit would carry over! Did the SHA change because I rebased something and forgot about it or is it because of the `Rebase and merge`?

Anyways, rebased and pushed it. Also verified that nothing panics with a 1gb test-corpus. 

Remaining steps should be fixing up documentation and maybe train a full model and verify that the implementation produces embeddings as expected?

**Comment by danieldk** [comment]
Any way the commit could change: rebasing, changed diff, changed commit message/metadata, etc.

Doing a test run sounds good!

**Comment by sebpuetz** [comment]
Turing seems busy with sticker and dpar running on the CPUs?
Might just give it a go on either shaw or tesniere then. Do you want to wait for the results before merging?

**Comment by danieldk** [comment]
Nope. Just waiting with the review until we are not at the swimming pool ;).

**Comment by sebpuetz** [comment]
I'm pretty happy with how we built this! Thanks for all the feedback ;)

Also excited about what else we can build in the future within our framework!

**Comment by sebpuetz** [comment]
First trained model with the new binary is on turing at `/home/sebastian/ff-deps-300dims-15epochs-default.fifu`. I compared some similarity queries to those from a model trained for the word embeddings course and they end up fairly similar (dominated by subwords). 

So I'm somewhat confident to say that the new implementation works at least like the old implementation!

**Pull request merged**
