### PR TITLE
Make SkipGramTrainer generic over Vocab.

### PR DESCRIPTION
**Pull request by sebpuetz**
This commit makes SkipGramTrainer generic over the vocabulary.

Mostly replacing `SubwordVocab` with `V` and adding trait bounds for `V`.

Content wise, biggest changes are made in `vocab`:

The `AssociatedIndices` trait defines a method to return a slice of indices associated with some lookup `idx`. `SimpleVocab` returns `Some(&[])`, regardless of the input, the implementation on `SubwordVocab` is just a copy of the `subword_indices_idx` method. 

`Trainer` delegates the `n_input_types` method to `Vocab`, since we can't calculate this number in `Trainer` without knowing the vocabulary type. Also adds to more flexibility if there'd be an additional input vocabulary involved.

The next PR should be restricted to adding a flag to `ff-train` and making some of the methods generic.

### CODE REVIEW

**Comment by sebpuetz** [comment]
> Looks generally good to me, though I don't like the name `AssociatedIndices`. I also find returning an empty slice for `SimpleVocab` a bit inelegant. It's cheap (probably doesn't even have a constant literal backing it), but I don't really like the distinction between a word index and subword indices.

I also didn't like that solution and considered returning a `None` for the `SimpleVocab`. But that would have weird implications. If the `idx` is out of bounds, the `input_indices` method would then return a `vec![idx]`, which I determined as an even worse option.


> Would it be possible to do something similar to TAFKA `rust2vec`, where we have one indices method that returns a single index for `SimpleVocab` and multiple indices for `SubwordVocab`?
> 
> https://github.com/finalfusion/finalfusion-rust/blob/d99608854a1694a64d25a0cd9480e50e934932cd/finalfusion/src/vocab.rs#L308

I'll try to come up with something like this. I think we still need the indirection of `Vocab::idx()` returning a `usize`, so we can use the returned index directly for the context lookup when the input vocabulary is `SubwordVocab`. But I think we can be more explicit about the return type of the `associated_indices` (or whatever other name we want for that Trait/method) by using an enum.

**Comment by sebpuetz** [comment]
This turned out to be a lot messier than expected.

I merged the `AssociatedIndices` trait into the `Vocab` trait and renamed the method to `idx2indices`. This method now returns `Result<Option<&[u64>, Error>`, returning `Error` if the lookup idx is out of bounds. At the call site in `SkipGramTrainer` I simply unwrap the result since that's what we've been doing all along with the returned `Option<&[u64]>` of the original indices method.

The `Option<&[u64]>` is matched and if it's `Some` the `Multiple` variant of the `Indices` enum is constructed. If it's `None`, the `Single` variant is built. `Multiple` is a wrapper around `Vec<u64>`, `Single` around `[u64; 1]`.

The `Indices` enum provides a `iter()` method, returning a wrapper around `&[u64]` implementing `Iterator<Item=u64>`.

The proposed commit adds some indirections and conditionals but I didn't observe a drop in performance. The time spent on my small test corpus stayed the same.

**Comment by sebpuetz** [comment]
An additional thought here:

If we stick to this solution we have no simple way to, e.g., train the constructed representations for OOV items. To get that to work we'd need a pendant to the `indices` and/or `subword_indices` methods on `SubwordVocab`.

**Comment by sebpuetz** [comment]
To add yet another thought to this mess:

I'm not sure whether I like the `input_indices(focus)` call in `SGD::update_sentence()`:
```Rust
for (focus, contexts) in self.model.trainer().train_iter_from(sentence) {
    // Update parameters for the token focus token i and the
    // context token j.
    let input = self.model.trainer().input_indices(focus);
    let input_embed = self.model.mean_input_embedding(&input);
    ...
}
```

If we want to enable training without subwords, this indirection is somewhat counter-intuitive. In my opinion, it'd be desirable to find a cheap abstraction for the return-type of `train_iter_from()` away from `(usize, IntoIterator<Item<usize>>)` and towards something more general. We would have to find a replacement for `usize` in both `focus` and `context`s, such that we can cheaply get out a single `usize` if it's just a single index (ideally without allocating something on the heap) and at the same time easily iterate over a list of indices.

I tried to come up with such an abstraction but ended up in lifetime-hell or with many additional heap allocations. Thus, I'd suggest to either go with some ad-hoc solution until we figure something out or to put this PR on ice for now and first take care of the dependency embeddings.

**Comment by danieldk** [comment]
If this PR is not necessary for dependency embeddings, let's let it cook for a bit longer.

**Comment by sebpuetz** [comment]
I'll close this PR for now, I think both #46 and #47 are better solutions, and rebasing this branch on master would be a pain.

**Pull request closed without merging**
