### PR TITLE
Merge finalfrontier into a single crate

### PR DESCRIPTION
**Pull request by danieldk**
Mostly moving files around. I put most of the `finalfrontier-utils` library stuff into the `io` module. The remainder is now in the `app` module.

We have a lot of crate-level symbols that should probably be removed over time (instead exposing just the submodules).

### CODE REVIEW

**Comment by sebpuetz** [comment]
Maybe this could be structured a bit more nicely with modules?

**Comment by danieldk** [comment]
> Maybe this could be structured a bit more nicely with modules?

Most stuff is in modules, but re-exported top-level. I think we could remove most top-level re-exports in a separate PR and instead just use modules (e.g. use `io::WriteModelBinary` rather than exposing this trait at the crate-level).

**Comment by sebpuetz** [comment]
I meant put things related to the binaries in some `training` folder. Probably not the most fitting name, but my idea was something similar to the `vocab` module.

**Comment by danieldk** [comment]
> I meant put things related to the binaries in some `training` folder. Probably not the most fitting name, but my idea was something similar to the `vocab` module.

There's `app` for that. Though I moved `thread_data*` and others to the `io` module, since the division there was fairly arbitrary anyway.

**Comment by danieldk** [comment]
If we want to do this, we should probably merge this PR before anything else, because rebasing this after other changes is a lot of work.

**Comment by sebpuetz** [comment]
Sure, I don't have any strong objections. I just took a quick glance earlier and won't get time to go through it thoroughly until tonight. Since most of this was shuffling things around, I don't think there's major things that could go wrong. While rebasing the other PRs we would probably find out if something went wrong. 

So if you're content with how this looks, you could also go ahead and merge this.

**Pull request merged**
