### PR TITLE
Refactor CLI using clap3

### PR DESCRIPTION
**Pull request by danieldk**
Largest changes:

- Generate command-line interface from structs/enums for better
  maintainability.
- Use several levels of subcommands for better partitioning of
  arguments, for example:

  ```
  finalfrontier --dims 200 corpus.txt embeddings.fifu \
      deps --use-root explicit --minn 4
  ```

Todo:

- [x] Bring back `completions` subcommand.
- [x] Test skipgram training. Tested some small skipgram training runs, seems to work correctly.
- [ ] Test dependency training.
- [x] Fix Clippy lints.
- [x] Set hard bound on clap version until clap 3 is released.

@sebpuetz still a draft, given the TODOs, but I thought I'd already show this, so that we can decide whether we want to go this direction.

### CODE REVIEW

**Comment by sebpuetz** [comment]
I'll try to check this out tomorrow during the day!

**Review by sebpuetz — APPROVED** [review]
I'm not very familiar with the code anymore, I went through the changes rather superficially and I didn't catch anything unexpected.

The behavior on the commandline is a bit odd since the `--help` output is always scoped on the current (sub-)command, so it's necessary to build up the command step-by-step. With the positional arguments on the main account, it's necessary to stub in some fake input and output paths to get any help output. Do you know if that's something that can be configured through `clap`?

**Comment by danieldk** [comment]
> I'm not very familiar with the code anymore, I went through the changes rather superficially and I didn't catch anything unexpected.

Same same. I had to reread a lot of code to understand bits and pieces. To make this PR tractable I am converting the clap-parsed `opts` structs to the internal configuration structs. I think this part could be simplified a lot, we could construct everything from the clap-parsed structs.

Another thing that makes parts difficult to re-read is that we use *a lot* of generics. I remember that in an early version we were doubting whether all the vocab and storage types should be trait implementations or enums. I think we opted for trait implementations because it makes extending finalfusion outside the crate easier. But then we are wrapping everything in emums anyway, to simplify downstream use. I hindsight, I think external extensibility is not really a big thing and it may have been easier to rely on enums more.

> The behavior on the commandline is a bit odd since the `--help` output is always scoped on the current (sub-)command, so it's necessary to build up the command step-by-step. With the positional arguments on the main account, it's necessary to stub in some fake input and output paths to get any help output. Do you know if that's something that can be configured through `clap`?

You don't have to stub input/output paths, something like:

```
$ finalfrontier train deps buckets --help
```

works to get the buckets help. It's still a bit annoying that you have to drill so deep to get that help. OTOH, the options are now nicely partitioned. Though I agree it would still be nice to get a complete overview of all options using just the top-level `finalfrontier` command. I'll take a look at the clap documentation.

**Comment by sebpuetz** [comment]
> You don't have to stub input/output paths, something like:
> 
> ```
> $ finalfrontier train deps buckets --help
> ```
> 
> works to get the buckets help. It's still a bit annoying that you have to drill so deep to get that help. OTOH, the options are now nicely partitioned. Though I agree it would still be nice to get a complete overview of all options using just the top-level `finalfrontier` command. I'll take a look at the clap documentation.

Oops, I mistyped the subcommand, that's why I got the same help message :laughing:

**Pull request merged**
